### ISSUE TITLE
502 Errors for Package Metadata

### ISSUE THREAD

**Issue by ayuhito** [jsdelivr/data.jsdelivr.com#60] opened 2023-10-30 22:59 UTC
Seems like we are getting 502 errors from the package metadata endpoint:

`"https://data.jsdelivr.com/v1/packages/npm/jquery"`
```
{
  "status": 502,
  "message": "Couldn't fetch versions for jquery."
}
```

**Comment by jimaek** [comment] 2023-10-31 06:43
The server running Redis that is required by the API crashed hard and was unresponsive. This is fixed now, I apologize for any issues caused by this.

**Closed by jimaek** 2023-10-31 06:43 UTC
Labels: bug
